### ISSUE TITLE
use specific photo option doesn't work 

### ISSUE THREAD

**Issue by fmobile** [sketch-hq/unsplash-sketchplugin#26]
Hi,

I am trying to use a specific photo from unsplash in sketch 58 and previously 57 so I tried using the search photo option and putting the url and the id but it doesn't work is this option is still available in the plugin?

thank you in advance

**Comment by maxdavid** [comment]
I believe this functionality was fixed in 5092c238b034241513c0a69c896c3c1c0d67f414 but an updated version of the plugin was never published. @bomberstudios may be able to help with that.

In the meantime @fmobile, cloning this repo and using `npm i && npm run build` to build the plugin locally should give you the feature you need.

**Comment by bomberstudios** [comment]
You're totally right, let me fix that!

**Comment by bomberstudios** [comment]
This was fixed on v1.0.9, just released
